### ISSUE TITLE
Code style w README.md

### ISSUE THREAD

**Issue by starsep** [szreder/ProGry2015#2]
Może warto byłoby jakiś code style ustalić?
Najlepiej wrzucić do jakiegoś README.md.

**Comment by szreder** [comment]
Tak, to słuszny pomysł. Powinienem znaleźć moment na klepnięcie tego w nocy i wrzucenie do readme i przyległości.

**Comment by szreder** [comment]
Szkic stylu i różnych takich:
- C++11 mile widziane (np. nullptr zamiast NULL).
- Nazewnictwo angielskie i camelCase (wielką literą klasy, namespace'y, stałe globalne, małą funkcje/metody, zmienne, stałe "tymczasowe").
- Commit messages też po angielsku. Standardowa praktyka, to jedna linijka z podsumowaniem zmian, linijka przerwy i potem ewentualnie dokładniejszy opis. Linijki nie powinny być dłuższe niż 76 znaków dla zgodności z różnymi gitowymi narzędziami (i wygodnie się czyta z konsoli).
- Spacje wokół operatorów binarnych.
- Symbol wskaźnika i referencji stawiamy przy nazwie zmiennej/argumentu, a nie przy typie. Rationale: te symbole wiążą w prawo. Jeśli coś takiego pojawia się przy typie wyniku, to:
```C++
void * fun()
```
- Wcięcia tabami.
- Długość wiersza: bez twardego limitu, use common sense.
- Jedna linijka robi jedną rzecz.
- Funkcje zaczynamy klamerką od następnego wiersza, ale warunki i pętle od tego samego. Pomijamy klamerki, jeśli wszystkie gałęzie warunku (albo ciało pętli) są jednolinijkowe. Jeśli gdziekolwiek potrzebne są klamerki, bo blok ma > 1 linijkę, klamerki wstawiamy wszędzie.
```C++
if (...) {
    ...
} else if (...) {
    ...
    ...
} else {
    ...
}```
- Const-correctness FTW
